# Generated by Django 2.0 on 2017-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=16)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('title', models.CharField(default='No title', max_length=200)),
            ],
        ),
    ]
