# Generated by Django 2.0 on 2017-12-14 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20)),
                ('title', models.CharField(default='No title', max_length=200)),
                ('thumbnail_link', models.CharField(default='', max_length=200)),
                ('last_played', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='logged_in_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('url', models.CharField(default=music.models.genId, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('shuffle', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('vote_skip_list', models.CharField(default='', max_length=2000)),
                ('current_playlistItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_playlistItem', to='music.PlaylistItem')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='last_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Room'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_item_room', to='music.Room'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='user_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
