# Generated by Django 2.0 on 2017-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171214_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
