# Generated by Django 2.0 on 2017-12-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20171208_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_state', models.IntegerField(default=0)),
                ('shuffle', models.IntegerField(default=0)),
                ('playing_youtube_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.PlaylistItem')),
            ],
        ),
    ]
