# Generated by Django 2.0 on 2017-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20171215_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='vote_skip_rate',
            field=models.FloatField(default=0.5),
        ),
    ]
