# Generated by Django 2.0 on 2017-12-20 14:55

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_room_vote_skip_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='url',
            field=models.CharField(default=music.models.genId, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='vote_skip_rate',
            field=models.FloatField(default=0.67),
        ),
    ]
