# Generated by Django 2.0 on 2017-12-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=False)),
            ],
        ),
    ]
