# Generated by Django 2.0 on 2017-12-10 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20171210_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playstate',
            name='playing_youtube_id',
        ),
        migrations.AddField(
            model_name='configitem',
            name='current_youtube_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='music.PlaylistItem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlayState',
        ),
    ]
