# Generated by Django 2.0 on 2017-12-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20171210_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='configitem',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
