# Generated by Django 2.0 on 2017-12-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_configitem_vote_skip_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='vote_skip_list',
            field=models.TextField(default=''),
        ),
    ]
