# Generated by Django 2.0 on 2017-12-13 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0010_auto_20171211_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='logged_in_user', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='playlistitem',
            old_name='date_added',
            new_name='last_played',
        ),
        migrations.RemoveField(
            model_name='configitem',
            name='current_youtube_id',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='play_count',
        ),
        migrations.AddField(
            model_name='configitem',
            name='playlistItem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.PlaylistItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='thumbnail_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='user_added',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='configitem',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.Room'),
            preserve_default=False,
        ),
    ]
